---
spring:
  jpa:
    hibernate.ddl-auto: none
    show_sql: false

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/pong_matcher_spring_development
    username: springpong
    password: springpong
